### ISSUE TITLE
Add support for Vite 5

### ISSUE THREAD

**Issue by metalmarker** [axe-me/vite-plugin-node#103]
Thanks for writing this awesome plugin. 

Given that deps were not updated yet to support Vite 5, we're seeing a warning: `unmet peer vite@^4.0.0: found 5.0.3`.

**Comment by vcardins** [comment]
Any updates on this?

**Comment by Detnator-Neo** [comment]
Hi.  I've got this issue too.  Any chance of this being resolved?  Thanks!

**Comment by nlwillia** [comment]
My impression is that plugins like this might be less relevant (or at least much simplified) once the new [runtime API](https://vitejs.dev/guide/api-vite-runtime) stabilizes.  It directly addresses the module-graph/HMR stuff by moving what [vite-node](https://github.com/vitest-dev/vitest/tree/main/packages/vite-node) was doing into the core.

**Comment by ZeldOcarina** [comment]
Any news on this one?

**Comment by palfaro91** [comment]
Will Vite v5 be supported?

**Comment by axe-me** [comment]
Hi guys, work's crazy busy for me recently again. I will find some time tmr to look into vite5 support. I know vite 5 has some breaking changes and removed some deprecated features this plugin uses. I will see what I can do to make this plugin supports vite5 and backward compatible at the same time.

**Comment by ZeldOcarina** [comment]
You are amazing!! Actually this plugin is the only way I found to make Node work with Vite so thank you so much!!!

**Comment by dirkluijk** [comment]
@axe-me No worries! Many thanks. The plugin is amazing indeed. Let me know if I can help you with anything.

As far as I could see, I was able to use the plugin with Vite 5 after upgrading its dependencies. So maybe we could even support Vite 4 and 5 simultaneously.

Alternatively, we could release a major version and include a compatibility matrix in the `README.md`. :)

**Comment by eugeniosegala** [comment]
Would it be possible to review and merge @dirkluijk's PR? 🙏 

https://github.com/axe-me/vite-plugin-node/pull/112

**Comment by dirkluijk** [comment]
In the end, I adopted part of the source code for my own plugin, without the SWC compiler and only supporting Express. The code is actually very straightforward, if anyone is interested, here is a gist:

https://gist.github.com/dirkluijk/e1a57bd09a13ee55695907e81c7123a2

**Comment by axe-me** [comment]
Hi guys, I just released a new version, 4.0.0, which supports vite 5. Most simple test cases are passed. However, there are some commonjs issues when I try to use it in my large project (because the buildSsrCjsExternalHeuristics option is removed in vite5). I will try to figure out a solution for that, but in the meantime please test out the version, and let me know if you find more issues.
