### ISSUE TITLE
Expose viteNodeApp after async operations

### ISSUE THREAD

**Issue by jazelly** [axe-me/vite-plugin-node#109]
Hi, we have an express server, which is designed to be initialized after some async operations.

A very small example could look like this
```
// app.ts
import Express from 'express';
function init() {
  const app = Express();
  app.use(...);
  return app
}

someAsyncFunction().then(() => {
   const app = init();
})

// would like to export here, but impossible
```

Node: `v18.19.0`
npm: `v9.6.7`

**Comment by jaypea** [comment]
you could return a promise in the export as shown in the cloudfunction example: https://github.com/axe-me/vite-plugin-node/blob/main/examples/cloudfunction/app.ts

```
// app.ts
import Express from 'express';
function init() {
  const app = Express();
  app.use(...);
  return app
}

export const viteNodeApp = someAsyncFunction().then(() => {
   return init();
})
```

**Comment by jazelly** [comment]
Thanks, that works!
