### ISSUE TITLE
After Upgrading from 3.1.0 to 4.0.0, can‘t bunddle output ESM

### ISSUE THREAD

**Issue by xiaofuyesnew** [axe-me/vite-plugin-node#114]
When upgrading from 3.1.0 to 4.0.0, it can't output ESM. Even I changed vite build.rollupOptions, it still out put cjs.

Any help to output ESM?

**Comment by skycoop** [comment]
I ended up looking at the code, there's a config option for the plugin called `outputFormat`
```ts
export default defineConfig({
  plugins: [
    ...VitePluginNode({
      ...
      outputFormat: "es",
    }),
  ]
});

**Comment by xiaofuyesnew** [comment]
> I ended up looking at the code, there's a config option for the plugin called `outputFormat`
> 
> ```ts
> export default defineConfig({
>   plugins: [
>     ...VitePluginNode({
>       ...
>       outputFormat: "es",
>     }),
>   ]
> });
> ```

Thx, tthis worked.
