### ISSUE TITLE
require is not defined - should I start with es6?

### ISSUE THREAD

**Issue by kewp** [axe-me/vite-plugin-node#12]
This was mentioned elsewhere.

Trying to use body-parser but getting an error.

```
11:14:57 AM [vite] Error when evaluating SSR module /node_modules/body-parser/index.js:
ReferenceError: require is not defined
    at /node_modules/body-parser/index.js:14:17
    at instantiateModule (/opt/homebrew/lib/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:68222:166)
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

ReferenceError: require is not defined
    at /node_modules/body-parser/index.js:14:17
    at instantiateModule (/opt/homebrew/lib/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:68222:166)
```

I want to wrap my head around something: vite uses es6 but express does not? So how does this plugin get around that? Am I suppose to be using express through es6 (I assume through babel) and only then use `vite-plugin-node`?

Thank you

**Comment by axe-me** [comment]
yea vite itself doesn't support `require` it can only use `import` aka ESM
if you are writing plain js code, you will need declare `type: "module"` in package.json
if you working with TS, you don't need to do any extra thing, vite support TS out of box.
