### ISSUE TITLE
Can't access my .env file value in app.ts

### ISSUE THREAD

**Issue by jcc1997** [axe-me/vite-plugin-node#15]
```typescript
// vite.config.ts
// ...
import { config } from 'dotenv';
config(...)
```
I can't get env by `process.env.MY_VALUE` in 'app.ts', but i can get it by `JSON.parse(JSON.stringify(process.env)).MY_VALUE`

I don't know if it's normal but I think at least it's wired.

**Comment by axe-me** [comment]
for .env usage see  https://vitejs.dev/guide/env-and-mode.html#env-files
