### ISSUE TITLE
NestJS + TypeORM support

### ISSUE THREAD

**Issue by richard-viney** [axe-me/vite-plugin-node#24]
This plugin looks great and I've been trying to get it going on a NestJS app, but have run into an issue that I think is caused by the fact that TypeORM `require`s all the entities it's told about via its config, which gives the error.

`SyntaxError: Cannot use import statement outside a module`

on the first line of the `*.entity.ts` file.

Looks like this is the line in TypeORM that does the require:
https://github.com/typeorm/typeorm/blob/master/src/util/DirectoryExportedClassesLoader.ts#L41

Is there some way to make this plugin work with NestJS and TypeORM? I found [this issue](https://github.com/typeorm/typeorm/issues/6974) on the TypeORM repo that seems potentially relevant, but states that ESM isn't supported.

I played around with running under `ts-node` and changing the `require()` to `import()`, but didn't really get anywhere with it as yet.

**Comment by vladimirgal1012** [comment]
Any updates on this ? Trying to get thinks working with this plugin + TypeORM

**Comment by richard-viney** [comment]
No updates from my side, I haven’t looked into this further since my last post. TypeORM 0.3 was released recently which might affect things here in some way.
