### ISSUE TITLE
Configuring this package in a NestJS Monorepo

### ISSUE THREAD

**Issue by oliverabclabs** [axe-me/vite-plugin-node#28]
I am running a NestJS monorepo using Nest CLI. I have multiple nest apps in this monorepo, and a shared library at the top level. I am unsure how to configure this package for such a setup. 

1. Do I put a `vite.config.ts` in each app? 
2. Can I run the apps with vite using Nest CLI? e.g `nest start app1`
3. How do I get a shared lib to work?

An example of using nestJS monorepo would be very much appreciated!

**Comment by GauBen** [comment]
Hey there, I created a complex monorepo that uses this plugin, nest, and a lot more: https://git.inpt.fr/inp-net/bonfire/

It's not yet documented, but you'll probably find what you need

**Comment by axe-me** [comment]
@GauBen thanks for helping out.
@oliverabclabs can you try his solution? 

closing this now, feel free to reopen this.
