### ISSUE TITLE
Any NestJS + Fastify example please

### ISSUE THREAD

**Issue by alexkharech** [axe-me/vite-plugin-node#30]

**Comment by ilterugur** [comment]
I need this too but I think it doesn't work with nest+fastify at this version as i see from NestHandler export.
@axe-me is there any quick fixes possible?

**Comment by drunkod** [comment]
+

**Comment by simplenotezy** [comment]
@axe-me I am trying to get it to work with fastify on a nest.js project, is there an example somewhere?
