### ISSUE TITLE
Runtime log are not displayed by vite

### ISSUE THREAD

**Issue by Tchoupinax** [axe-me/vite-plugin-node#31]
Hello!

I am testing your plugin and I want to have a watch server that restart for each modification. For doing this, I use `nodemon`.

```
nodemon -e ts --exec vite
```

The watch mode seems to work correctly but my console is filled by vite.

```
vite v2.8.6 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 134ms.

```

Could you know how to display logs or simple `console.log` ? 

Thank you :)

**Comment by axe-me** [comment]
console.log works fine for me.

and I dont think you need use nodemon with vite, the main purpose of this plugin is doing HMR which replace the server restart.

**Comment by Tchoupinax** [comment]
Hello, 

I tested and you got right. It is not very natural because I have the habit to see the server restarting on each file save >.<
I do know if it exists an option to tell that the changes has been taken

Thank for your job, it works fine!
