### ISSUE TITLE
Using with standard node server?

### ISSUE THREAD

**Issue by lucas-jones** [axe-me/vite-plugin-node#39]
Is there a way to use this with without one of the adapters. I have just a standard NodeJS that doesn't use any framework (It just runs a WebSocket server)

**Comment by vinicius73** [comment]
Some here, I want to use it in a background worker project.

**Comment by axe-me** [comment]
ofc, i just made an example, see https://github.com/axe-me/vite-plugin-node/blob/main/examples/node/app.ts

**Comment by lucas-jones** [comment]
Sorry I mean non-http based applications?
