### ISSUE TITLE
Vite build support?

### ISSUE THREAD

**Issue by delaneyj** [axe-me/vite-plugin-node#4]
Would be great, especially for Docker deployment, to be able to do something like `vite build` where it uses rollup to deliver a tree shaken version of your node server to reduce build size and runtime ts compilation.  While the runtime compiling is fast its also adding extra watcher and stuff that shouldn't be on in production.

**Comment by axe-me** [comment]
This is a good idea, I will find time to figure this out.

**Comment by pranaypratyush** [comment]
Kinda assumed it was already in place. Now eagerly waiting for it as a small project reaches production.

**Comment by N0tExisting** [comment]
You could probably use a [SSR build](https://vitejs.dev/guide/ssr.html#building-for-production) for that!

@maninak For Source maps you need to set [`build.sourcemap`](https://vitejs.dev/config/#build-sourcemap) to `true`

**Comment by axe-me** [comment]
This should work with the new 0.0.17 release! 

dup #20
