### ISSUE TITLE
Tiny typos in vite.config.ts snippet

### ISSUE THREAD

**Issue by RinatValiullov** [axe-me/vite-plugin-node#5]
Tiny typos

- Missing closing parenthesis `)`
https://github.com/axe-me/vite-plugin-node/blob/89392208aaddb3649bc8a53606a58aef43fdacb6/README.md#L47

- Mmissing comma `,`
https://github.com/axe-me/vite-plugin-node/blob/89392208aaddb3649bc8a53606a58aef43fdacb6/README.md#L38

**Comment by axe-me** [comment]
ah, thanks for letting me know this. code in markdown is hard, lol

**Comment by axe-me** [comment]
fixed
