### ISSUE TITLE
Publish README.md to GitHub

### ISSUE THREAD

**Issue by yuchenshi** [axe-me/vite-plugin-node#51]
Right now, https://www.npmjs.com/package/vite-plugin-node is missing a README.md.

It will be nice if you could copy the `README.md` from project git root into `packages/vite-plugin-node` at prepublish and include it in [package.json `files`](https://github.com/axe-me/vite-plugin-node/blob/652bec7484b8a9122df3cd11cf10dd6152960607/packages/vite-plugin-node/package.json#L23).

**Comment by axe-me** [comment]
published
