### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by Archsx** [axe-me/vite-plugin-node#54]
I've clone the repo, and cd example directory(express),and install packages, and `npm run dev`, when I try to entry `http://localhost:3699/ip`, I got error: 

ReferenceError: fetch is not defined

**Comment by kasbah** [comment]
Try running it with Node >= 18. Global `fetch` was introduced in Node 18.

**Comment by Archsx** [comment]
> Try running it with Node >= 18. Global `fetch` was introduced in Node 18.I

I've updated Node to v18.6 but still get the error, maybe the example is just provide some idea about how to use the plugin , not runnable

**Comment by kasbah** [comment]
I think they should be runnable but I can't run the express example either (getting a different error). 

Have you tried the `npm run dev-flag` script? That seems like it's trying to address the lack of `fetch`.

**Comment by axe-me** [comment]
@kasbah what error did you get ?
the express example works fine for me under node 18
