### ISSUE TITLE
Vite-plugin-ssr support

### ISSUE THREAD

**Issue by stychu** [axe-me/vite-plugin-node#57]
Hi, would love to have this working with https://vite-plugin-ssr.com/ from the first try I wasn't able to get it working all togeter :(
I wish. this functionality would be available for my development. Any suggestions ?

**Comment by axe-me** [comment]
`vite-plugin-ssr` doesn't have hmr already?

**Comment by axe-me** [comment]
closing for house keeping, feel free to reopen.
