### ISSUE TITLE
Do you plan to support Vite 3.0?

### ISSUE THREAD

**Issue by shuuuuun** [axe-me/vite-plugin-node#59]
Vite 3.0 was released on 07/13/2022.
https://github.com/vitejs/vite/releases/tag/v3.0.0
https://vitejs.dev/blog/announcing-vite3.html

vite-plugin-node currently cannot be used with Vite 3.0 because `"vite":"^2.9.8"` is specified in peerDependencies.
https://github.com/axe-me/vite-plugin-node/blob/652bec7484b8a9122df3cd11cf10dd6152960607/packages/vite-plugin-node/package.json#L40

It would be great if you could support Vite 3.0.
Thank you.

**Comment by sebastiangug** [comment]
I pretty much installed vite 3 and ignored that warning, didn't seem to be a problem. 

Sadly I don't think this package is maintained any longer, haven't seen anyone replying/fixing anything or posting any new versions, which is fair enough. 

Might give it a go at forking it and fixing some of the issues as I'd like to be able to use this with nestjs & graphql.

**Comment by vova-white** [comment]
`Might give it a go at forking it and fixing some of the issues as I'd like to be able to use this with nestjs & graphql.`
@sebastiangug I made a small [starter for nestjs(fastify)](https://github.com/vova-white/nest-fastify-graphql-vite) with vite and graphql. If you haven't solved your problem yet, maybe this will help you.

**Comment by jaybe78** [comment]
@sebastiangug  @vova-white  @shuuuuun what about https://www.npmjs.com/package/vite-node ?
Has anyone used it ?

**Comment by wobsoriano** [comment]
that redirects to vitest @jaybe78

**Comment by qeleb** [comment]
For anyone who finds this and VItePluginNode is still outdated... I've created a small, lightweight, and up-to-date version [here](https://github.com/qeleb/Vite-Fastify-Dev-Plugin).

It is specifically designed for Fastify, but can be easily switched to any of the other supported frameworks by replacing lines 35-36 with the contents of one of [these functions](https://github.com/axe-me/vite-plugin-node/tree/main/packages/vite-plugin-node/src/server)

**Comment by axe-me** [comment]
sorry, tons of things are going on in work and life. 
pushed out a new 2.0.0 for support vite 3, please try it out.
