### ISSUE TITLE
Is it possible to pass your own CLI commands to boot up the server?

### ISSUE THREAD

**Issue by jaequery** [axe-me/vite-plugin-node#60]
Is it possible to define your own commands when starting the Nest server?

Currently, it's just "vite" which looks at your vite.config.json to launch the Nest server:

```
export default defineConfig({
  server: {
    port: 3000,
  },
  plugins: [
    ...VitePluginNode({
      adapter: 'nest',
      appPath: './src/main.ts',
      tsCompiler: 'swc',
      exportName: 'app',
    }),
  ] as unknown as [PluginOption],
  optimizeDeps: {
    // Vite does not work well with optionnal dependencies,
    // mark them as ignored for now
    exclude: [
      '@nestjs/microservices',
      '@nestjs/websockets',
      'cache-manager',
      'class-transformer',
      'class-validator',
      'fastify-swagger',
      'mock-aws-s3',
    ],
  },
});
```

But when you need to run Nest by passing some other arguments, for eg; with REPL, you have to run the server like this:
$ npm run start -- --entryFile repl

How can I do this using Vite?

**Comment by axe-me** [comment]
sry, this plugin is meant to use for HTTP server. but not for cli.
