### ISSUE TITLE
can this be mixed into a vite app as api mock server?

### ISSUE THREAD

**Issue by beetaa** [axe-me/vite-plugin-node#7]
It seems that the plugin is aimed to backend app development. how about and how to mixed it into a vite app as api mock server? It will perfect for someone who want to rule the frontend and backend at the same time.

**Comment by axe-me** [comment]
Hi @beetaa, you may not need this plugin to implement an API mock server. Vite itself already supports the user to add custom middleware to the dev server. You could just use that feature to write a simple plugin to put in your mock data, for example:
```ts
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [{
	name: 'mock-server',
    configureServer: (server) => {
      server.middlewares.use('/data-path', (req, res, next) => {
        // return your mock data.
		res.end('this is mock data')
      })
    },
    apply: 'serve'
  }]
})

```

But if you really want to use this plugin to implement your mock server, I don't see a blocker for doing that.

Happy coding!

**Comment by axe-me** [comment]
closing this. If you still got questions about this plugin feel free to ask me.
