### ISSUE TITLE
NestJS, SocketIO not working

### ISSUE THREAD

**Issue by angelhdzmultimedia** [axe-me/vite-plugin-node#71]
I have a working Nest server and a Vue3/Quasar client using SocketIO.
Then I switch to vite-plugin-node and the client has errors about SocketIO, 404 errors and can't connect.

I read another 2021 issue saying Web sockets not working.

Is there a fix on 2023?

**Comment by NatSavage** [comment]
same here. i ended up switching back to the default nest cli server. It has definitely got something to do with vite as i tested the nest websocket sample project with vite and got the same thing
![image](https://user-images.githubusercontent.com/43824666/216793946-ad76c4cb-de26-4338-b061-2b91d44c1b72.png)
![image](https://user-images.githubusercontent.com/43824666/216793953-590032ec-6220-4b35-9f5d-90345e56a2e6.png)

**Comment by matteobad** [comment]
Any updates on this?

**Comment by angelhdzmultimedia** [comment]
> Any updates on this?

I don't know. The lack of info stopped me from attempting anything beyond. Hope this gets solved in the future. Have a nice rest of the day
