### ISSUE TITLE
nestjs Error when evaluating SSR module

### ISSUE THREAD

**Issue by productdevbook** [axe-me/vite-plugin-node#8]
12:32:41 PM [vite] Error when evaluating SSR module /src/app.module.ts:
Error: Failed to resolve import "src/guards/gql-auth.guard" from "src/auth/auth.module.ts". Does the file exist?
    at formatError (/s/node_modules/vite/dist/node/chunks/dep-972722fa.js:51153:46)
    at TransformContext.error (/s/node_modules/vite/dist/node/chunks/dep-972722fa.js:51149:19)
    at normalizeUrl (/s/node_modules/vite/dist/node/chunks/dep-972722fa.js:74554:26)
    at async TransformContext.transform (/s/node_modules/vite/dist/node/chunks/dep-972722fa.js:74687:57)
    at async Object.transform (/s/node_modules/vite/dist/node/chunks/dep-972722fa.js:51354:30)
    at async transformRequest (/s/node_modules/vite/dist/node/chunks/dep-972722fa.js:67098:29)
    at async instantiateModule (/s/node_modules/vite/dist/node/chunks/dep-972722fa.js:73732:10)

**Comment by productfrontenddeveloper** [comment]
I can ship in 2-3 weeks. I don't know how to break this into little pieces.

**Comment by productfrontenddeveloper** [comment]
import { GqlAuthGuard } from 'src/guards/gql-auth.guard'; -> import { GqlAuthGuard } from '../../guards/gql-auth.guard'; and fixed why src problem ?

**Comment by productfrontenddeveloper** [comment]
new problem

```
5:15:49 PM [vite] Error when evaluating SSR module /src/app.module.ts:
ReferenceError: require is not defined
    at /src/app.module.ts:40:11
    at async instantiateModule (/s/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75018:9)
5:15:49 PM [vite] Error when evaluating SSR module ./src/main.ts:
ReferenceError: require is not defined
    at /src/app.module.ts:40:11
    at async instantiateModule (/s/node_modules/vite/dist/node/chunks/dep-1be34a63.js:75018:9)
(node:30397) UnhandledPromiseRejectionWarning: ReferenceError: require is not defined
    at /src/app.module.ts:40:11
  
```

**Comment by unlight** [comment]
#11 Looks like related

**Comment by axe-me** [comment]
do you have any `require`s in your `app.module.ts` ?
vite not support commonjs style requires, try use `import`

**Comment by productfrontenddeveloper** [comment]
> do you have any `require`s in your `app.module.ts` ?
> vite not support commonjs style requires, try use `import`

yes fixed.  new problem

ReferenceError:: __dirname is not defined
    at typeormModuleOptions (/src/config/database.config.ts:17:40)
    at InstanceWrapper.eval [as metatype] (/src/config/database.config.ts:30:17)
    
   ```
 
    import { registerAs } from '@nestjs/config';
import { join } from 'path';
import { ConnectionOptions } from 'typeorm';
function typeormModuleOptions(): ConnectionOptions {
  return {
    type: 'postgres',
    host: process.env.GENERAL_DATABASE_HOST,
    port: parseInt(process.env.GENERAL_DATABASE_PORT),
    username: process.env.GENERAL_DATABASE_USERNAME,
    password: process.env.GENERAL_DATABASE_PASSWORD,
    database: process.env.GENERAL_DATABASE_NAME,
    synchronize: Boolean(process.env.TYPEORM_SYNC),
    entities: [join(__dirname, '../**/**/*entity{.ts,.js}')],
    migrationsRun: true,
    migrations: [join(__dirname, '../migration/**/*{.ts,.js}')],
    migrationsTableName: 'migration_typeorm',
   
   ```

**Comment by productfrontenddeveloper** [comment]
and delete new problem. 

```
[Nest] 60798  - 09/06/2021, 9:09:33 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
```

**Comment by productfrontenddeveloper** [comment]
9:22:53 PM [vite] Error when evaluating SSR module /src/app.module.ts:
TypeError: Cannot read property 'KEY' of undefined


9:22:53 PM [vite] Error when evaluating SSR module ./src/main.ts:
TypeError: Cannot read property 'KEY' of undefined

**Comment by productfrontenddeveloper** [comment]
```
import { ConfigFactory, registerAs } from '@nestjs/config';
import { ConnectionOptions } from 'typeorm';
import { ConfigService } from '@nestjs/config';
import * as path from 'path';


export const typeormModuleOptions: ConfigFactory<ConnectionOptions> = (
  configService?: ConfigService,
) => {

  const entitiesPath = path.resolve(__dirname, '../**/entities/*{.ts,.js}');
  const migrationPath = path.resolve(__dirname, '../../migration/*{.ts,.js}');
  const commonConfigs = {
    entities: [entitiesPath],
    migrations: [migrationPath],
    cli: {
      migrationsDir: 'migration',
    },
  };
  if (configService) {
    return {
      type: 'postgres',
      host: configService.get('GENERAL_DATABASE_HOST'),
      port: configService.get<number>('GENERAL_DATABASE_PORT'),
      username: configService.get('GENERAL_DATABASE_USERNAME'),
      password: configService.get('GENERAL_DATABASE_PASSWORD'),
      database: configService.get('GENERAL_DATABASE_NAME'),
      synchronize: configService.get<boolean>('TYPEORM_SYNC'),
      ...commonConfigs,
    };
  }

  return {
    type: 'postgres',
    host: process.env.GENERAL_DATABASE_HOST,
    port: parseInt(process.env.GENERAL_DATABASE_PORT),
    username: process.env.GENERAL_DATABASE_USERNAME,
    password: process.env.GENERAL_DATABASE_PASSWORD,
    database: process.env.GENERAL_DATABASE_NAME,
    synchronize: Boolean(process.env.TYPEORM_SYNC),
    ...commonConfigs,
  };
};

export default registerAs('database', typeormModuleOptions);
```

**Comment by productfrontenddeveloper** [comment]
[Nest] 70663  - 09/06/2021, 10:26:38 PM     LOG [InstanceLoader] AwsSdkModule dependencies initialized +0ms
[Nest] 70663  - 09/06/2021, 10:26:38 PM     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +0ms
[Nest] 70663  - 09/06/2021, 10:26:38 PM     LOG [InstanceLoader] RedisModule1 dependencies initialized +11ms
[Nest] 70663  - 09/06/2021, 10:26:38 PM     LOG [InstanceLoader] GraphQLModule dependencies initialized +0ms
[Nest] 70663  - 09/06/2021, 10:26:38 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +581ms
[Nest] 70663  - 09/06/2021, 10:26:38 PM   ERROR [ExceptionHandler] No metadata for "User1" was found.
EntityMetadataNotFoundError: No metadata for "User1" was found.

dont used User1, i am used User -> why new name change add

**Comment by productfrontenddeveloper** [comment]
> please see [#9 (comment)](https://github.com/axe-me/vite-plugin-node/issues/9#issuecomment-906658693) for the `__dirname` issue

dir delete and new problem up

```
https://github.com/axe-me/vite-plugin-node/issues/8#issuecomment-913823549
```

**Comment by axe-me** [comment]
I'm afraid I need you to provide a repro for this User model issue.

**Comment by axe-me** [comment]
close for now due to inactive.
