### ISSUE TITLE
Node Server doesn't start automatically

### ISSUE THREAD

**Issue by kefniark** [axe-me/vite-plugin-node#85]
## Description
I've been using `vite-plugin-node` with express and both REST and GraphqlAPI for few month and it works quite well so far.
But there is one thing that annoy me and I wonder if there is a way through config to do something.

Basically when I use `vite dev`, I get the vite log 
```
VITE v4.0.4  ready in 335 ms
api:start:
api:start:   ➜  Local:   http://localhost:3200/
api:start:   ➜  Network: http://172.18.0.4:3200/
```
But probably because of the HMR, the server and code are only executed when a query is done.
So starting the server, only start vite, not really the node server, it need a query to finally notice and start the API.

It's really annoying from a dev perspective because:
* the first query is always really slow (it boot everything, connect to db, ...), even if it had 2-3 min to do it before.
* if there are some config, deps issues, we don't notice the problem unless a query is made to the server

Is there a way to force vite to execute the `viteNodeApp` automatically on startup?

I thought about adding some healthcheck logic around to request a useless endpoint like `/health`.
But it felt like an ugly workaround.

**Comment by pquoctuanno1** [comment]
Hi @xmuller. I have read through and tried to apply your method, but I think it has some problems. I only want to connect to the db when fastify is ready.
```
if (import.meta.env.DEV) {
	fastify.addHook('onReady', onReady)
}
if (import.meta.env.PROD) {
	fastify.listen({ host: '0.0.0.0', port: 10000 }).then(onReady)
}
```
So your way the function "onReady" will not be executed, your way only executes functions that run directly in the file "config.appPath"

**Comment by xmuller** [comment]
Hello !

Yes, to be fair I didn't think a lot about the code I wrote.
My pull request works probably only in my case which is to init my NestJs backend at startup to check modules instanciation.

In the end I don't use this plugin. I do the classic build and nodemon with https://github.com/SukkaW/rollup-plugin-swc.
I will probably close my pull request because it's clear that this code has flaws.

As far as my research goes, the only benefit of another plugin would be to have a dev environnement that integrate the [HMR  API](https://vitejs.dev/guide/api-hmr.html) with one or many backend. 
Nothing seems to prevent it but I don't know if it's worth the effort  🤷‍♂️

**Comment by xmuller** [comment]
> Hi @xmuller. I have read through and tried to apply your method, but I think it has some problems. I only want to connect to the db when fastify is ready.
> 
> ```
> if (import.meta.env.DEV) {
> 	fastify.addHook('onReady', onReady)
> }
> if (import.meta.env.PROD) {
> 	fastify.listen({ host: '0.0.0.0', port: 10000 }).then(onReady)
> }
> ```
> 
> So your way the function "onReady" will not be executed, your way only executes functions that run directly in the file "config.appPath"

By default the only way the vite server load modules is from the handler given here: https://github.com/axe-me/vite-plugin-node/blob/main/packages/vite-plugin-node/src/server/fastify.ts based on the viteNodeApp that is exported from your main file.

If you want to load execute something when fastify is ready you cantry to call it yourself first.
```
if (import.meta.env.DEV) {
	fastify.addHook('onReady', onReady)
        await fastify.ready()
}
export const fastify as viteNodeApp
```

**Comment by GeoffreyBooth** [comment]
I have a Node app that doesn’t listen at all, so I needed a way to start it when run via `vite-plugin-node`. This is what I came up with:

#### `vite.config.js`

```js
import { defineConfig } from 'vite'
import { VitePluginNode as vitePluginNode } from 'vite-plugin-node'


export default defineConfig({
	build: {
		lib: {
			entry: new URL('lib/main.js', import.meta.url).pathname,
		},
	},
	server: {
		port: 3000,
	},
	plugins: [
		...vitePluginNode({
			adapter({ app, req, res }) {
				app(req, res)
			},
			appPath: './entry.js',
			exportName: 'viteNodeApp',
		}),
	],
})

// Trigger server initialization by making a request to it; 
// and keep restarting it after HMR by sending new requests:
setInterval(() => {
	try {
		fetch('http://localhost:3000')
	} catch {}
}, 1000)
```

#### `entry.js`

```js
let initialized = false
/**
 * Export for vite-node-server.
 */
export function viteNodeApp(_request, response) {
	if (!initialized) {
		initialized = true
		initialize()
	}

	response.statusCode = 200
	response.end()
}

async function initialize() {
	// App goes here
}
```

**Comment by axe-me** [comment]
Sorry I'm late to the party. I just added an `initAppOnBoot` option, when it is set to true, your app will be loaded once the vite server starts. it's released in 3.1.0, please upgrade and test it out, let me know if it works for you please.

**Comment by axe-me** [comment]
closing this for now, feel free to reopen it if you have any questions.

**Comment by PurpleTape** [comment]
Hello! I'm facing a similar problem. I'm trying to use this together with Nest (`initAppOnBoot: true`):
```
  VITE v5.0.2  ready in 180 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.0.199:5173/
  ➜  press h + enter to show help

[Nest] 15975  - 11/24/2023, 2:50:14 PM     LOG [NestFactory] Starting Nest application...
[Nest] 15975  - 11/24/2023, 2:50:14 PM     LOG [InstanceLoader] AppModule dependencies initialized +16ms
[Nest] 15975  - 11/24/2023, 2:50:14 PM     LOG [InstanceLoader] NestjsGrammyModule dependencies initialized +0ms
[Nest] 15975  - 11/24/2023, 2:50:14 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 15975  - 11/24/2023, 2:50:15 PM     LOG [InstanceLoader] GrammyCoreModule dependencies initialized +368ms
[Nest] 15975  - 11/24/2023, 2:50:15 PM     LOG [InstanceLoader] BotsModule dependencies initialized +0ms
[Nest] 15975  - 11/24/2023, 2:50:57 PM     LOG [NestApplication] Nest application successfully started +42153ms
```
But the application finally starts (log: `LOG [NestApplication] Nest application successfully started +42153ms`) only when I manually go to the address `http://192.168.0.199:5173/` in the browser.

What can be done in such a situation?

**Comment by droutin** [comment]
Same problem as @PurpleTape
