### ISSUE TITLE
`vite-plugin-node` vs `vite-node`

### ISSUE THREAD

**Issue by Jazcash** [axe-me/vite-plugin-node#94]
What are the differences between these projects? Is there any reason I should choose one over the other?

**Comment by taka1156** [comment]
https://twitter.com/antfu7/status/1446536501399998465?s=46&t=J-9KJQx5XojCynDmMGNd8g

**Comment by axe-me** [comment]
vite-node is mostly for run one time script, don't think it can do hmr for node http server
