### ISSUE TITLE
I used the nestjs and vite-plugin-node  example, they threw this err,,,what makes it so

### ISSUE THREAD

**Issue by DankeBIBI** [axe-me/vite-plugin-node#98]
VITE v4.4.9  ready in 589 ms

  ➜  Local:   http://127.0.0.1:3000/
  ➜  Network: use --host to expose
  ➜  press h to show help
[Nest] 22660  - 2023/08/28 17:40:32     LOG [NestFactory] Starting Nest application...
[Nest] 22660  - 2023/08/28 17:40:32     LOG [InstanceLoader] AppModule dependencies initialized +18ms
[Nest] 22660  - 2023/08/28 17:40:32     LOG [RoutesResolver] AppController {/}: +33ms[Nest] 22660  - 2023/08/28 17:40:32     LOG [RouterExplorer] Mapped {/, GET} route +7ms
[Nest] 22660  - 2023/08/28 17:40:32     LOG [NestApplication] Nest application successfully started +4ms
[Nest] 22660  - 2023/08/28 17:40:32   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'getHello')TypeError: Cannot read properties of undefined (reading 'getHello')

**Comment by DankeBIBI** [comment]
right,This service started running when I changed tsCompiler:'esbuild' to 'swc'

**Comment by axe-me** [comment]
yea, nestjs need to use swc
