### ISSUE TITLE
Module '"http"' has no default export.

### ISSUE THREAD

**Issue by HishamAli81** [axe-me/vite-plugin-node#99]
## ISSUE

I'm trying to create a shared library that contains the standard vite configurations that I'd like to use in all my applications. When I create the shared library and try building it using the `tsc --outDir dist` command, I get the following error:

```bash
/node_modules/.pnpm/vite-plugin-node@3.0.2_@swc+core@1.3.92_vite@4.4.11/node_modules/vite-plugin-node/dist/index.d.ts(2,13): error TS1192: Module '"http"' has no default export.
```

Here's a sample `src/index.ts`:

```typescript
import { defineConfig } from 'vite';
import { VitePluginNode } from 'vite-plugin-node';

export default defineConfig({
  plugins: [
    ...VitePluginNode({
      adapter: 'fastify',
      appPath: './src/main.ts',
      exportName: 'viteNodeApp',
      tsCompiler: 'esbuild',
    }),
  ],
});
```

## PROPOSAL

Fix the import here https://github.com/axe-me/vite-plugin-node/blob/main/packages/vite-plugin-node/src/index.ts#L1 to explicitly import the `IncomingMessage` and `ServerResponse` types.

**Comment by HishamAli81** [comment]
I've created this PR to fix the issue: https://github.com/axe-me/vite-plugin-node/pull/100

**Comment by axe-me** [comment]
thanks, merged, will release it in next version
